<?php 
$baseUrl = $block->getBaseUrl();
$customText = $block->getCustomText();
$customTextRequire = $block->getCustomTextRequire();
?>
<div class="delete-account-main">
	<form method="POST" action="<?=$baseUrl;?>deleteaccount/Customer/Delete">
		<input type="checkbox" id="confirm-delete" name="confirm-delete" value="1" style="display: none" checked="checked">
        <input type="button" class="action primary" id="delete-account" value="Delete your account">

        <br><br>
        <p> <?=$block->getCustomText();?></p>
        <br/><br/>
        <textarea name="feedback" id="feedback" style="display: none"></textarea>
	</form>
</div>
<div id="popup-modal" style="display:none;">
    <textarea name="customtext" id="customtext" required></textarea>
</div>
<input type="text" style="display: none;" value="<?= $customTextRequire;?>" id="customTextRequire">